spring.application.name=EcommerceOrderTracking

# Server configuration
server.port=8081

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Settings
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Spring Mail Configuration (Dummy config - Update with real SMTP to send actual emails)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anuragpanjre79@gmail.com
spring.mail.password=vflo iqbk skbi stzt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true